### ISSUE TITLE
Pulling through the pre-tax price from landing page.

### ISSUE THREAD

**Issue by WHitter1** [facebookincubator/facebook-for-magento#22]
Using the pixel tracker tool I can see the pixel is firing the correct price on the landing page, however within the product catalogue on Facebook the pre-tax price is being showed. Can anyone help as to why this might be?

Thanks in advance

**Comment by sammul** [comment]
Hi, can you share us your website url and Facebook page url so that we can compare them? Thanks

**Comment by dmitridr** [comment]
Hi, Thanks for writing in to us. I have a couple of more follow up questions, and some comments that may help.

- Is this the case for all products or only some type? We recently fixed this for bundled products.
- Can you confirm that you have the latest version of the extension?
- If you have a unique Tax setup, could you give us the details as to how you have it set up so that we can try to set it up ourselves in this way on our own servers in order to reproduce the problem?

As you can see in our [code for calculating the price to put into feed](https://github.com/facebookincubator/facebook-for-magento/blob/master/app/code/community/Facebook/AdsExtension/Model/FBProductFeed.php#L723) We use the Mage tax helper in order to get the tax. If you are not seeing the tax in the feed on the latest version, perhaps there is some kind of issue with the helper.

**Comment by WHitter1** [comment]
Hi,

Thanks for the feedback.

It was on all products however since Tuesday the prices have updated to display the correct price. I have it set to a daily scheduled fetch and it is still displaying the correct price so hopefully the issue is resolved.

Thanks

**Comment by dmitridr** [comment]
Weird that it resolved itself. But glad that the issue is resolved, feel free to re-open if it happens again.
