### ISSUE TITLE
Notice: Undefined variable: format (Observer.php on line 166)

### ISSUE THREAD

**Issue by cameraki** [facebookincubator/facebook-for-magento#27]
Hey

I am getting this notice daily

Notice: Undefined variable: format in /home/cameraki/public_html/gripup/app/code/community/Facebook/AdsToolbox/Model/Observer.php on line 166

Since a few weeks ago. This is the last line of the method internalGenerateFacebookProductFeed()

Can't seem to find my version number. Any ideas?

**Comment by dmitridr** [comment]
Hey,

Seems like you are using a very old version of the plugin, since you have `AdsToolbox` in your path, but any version released in the last 6 months should be `AdsExtension`.

I recommend upgrading from our [latest releases](https://github.com/facebookincubator/facebook-for-magento/releases).

I checked [that section of the code](https://github.com/facebookincubator/facebook-for-magento/blob/master/app/code/community/Facebook/AdsExtension/Model/Observer.php#L169) but it looks like format is defined, so maybe we fixed this a really long time ago.

**Comment by cameraki** [comment]
Thanks for the reply.

Have just updated it, guessed that could be the issue.

Assuming this will fix the problem so will close it.
