### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by mblatt** [facebookincubator/facebook-for-magento#35]
I am using a CDN for my media folder and the extension gives the product feed link as:
https://cdn.my-domain.com/media/facebook_adstoolbox_product_feed.tsv

But the file does not exist there but only in:
https://www.my-domain.com/media/facebook_adstoolbox_product_feed.tsv

Is there a way to hardcode a path of my own choice?

Regards,
Marcus

**Comment by mengyingdu** [comment]
Hi @mblatt ,

These [lines](https://github.com/facebookincubator/facebook-for-magento/blob/master/app/code/community/Facebook/AdsExtension/Model/FBProductFeed.php#L467-L469) is to get the path of feed. 
If you want to hardcode, I would suggest that you take a look at this document: https://techbandhu.wordpress.com/2013/05/08/magento-get-directory-paths-get-base-urls-get-urls-in-static-block-get-secure-url/

Thanks.

**Comment by mblatt** [comment]
okay. so I can change "Mage::getBaseDir(Mage_Core_Model_Store::URL_TYPE_MEDIA).'/';" into something like "https://www.my-domain.de/my-feeddirectory". Right? Sorry but I am not a progammer and Facebook support told me that the module comes not from Facebook at all and I shall ask here...

**Comment by mengyingdu** [comment]
Hi @mblatt ,

Okay, I understand. Since you tell us you want to customize and develop by yourself, i assume you have sophisticate development experience about your site.

Can you try to replace this [line](https://github.com/facebookincubator/facebook-for-magento/blob/master/app/design/adminhtml/default/default/template/facebook_ads_extension/fae_index.phtml#L48) as:
feedUrl: 'https://www.my-domain.com/media/facebook_adstoolbox_product_feed.tsv' 
Let me know whether it works.

Thanks.

**Comment by mblatt** [comment]
It worked! Great, thanks!
