### ISSUE TITLE
Backend not working: cannot read property 'diaSettingId' of undefined

### ISSUE THREAD

**Issue by Sprite-IT** [facebookincubator/facebook-for-magento#42]
We installed the extention on a magento 1.9.3.6 version, but the backend is not working.
When I go the the Facebook Ads Extension page I just see the header image and nothing else.

When I open my developer consule I see the following error.
Uncaught TypeError: Cannot read property 'diaSettingId' of undefined

We already cleared all caches

**Comment by dmitridr** [comment]
Hey,

There's likely an exception in the backend when fetching your sample products. 
If you email us the source code of the page with the header image we can confirm that. (ads_extension@fb.com). Unfortunately we still don't know the problem here, do you have any server logs you can search for exceptions caused by the plugin? I would try to search those for `facebook` and post anything you find here.

There are two similar issues on this problem : #11 #21 
You can also try the resolutions suggested in those.

**Comment by mpalasis** [comment]
I get 
`Uncaught SyntaxError: Unexpected token }      (index):497 `

and index:497 is:
`   ,samples:` <--- this is empty
`  }` <-- 497 is here
`};`
and 
`Uncaught TypeError: Cannot read property 'diaSettingId' of undefined`

My currency is set to EUR no other currencies are used, conversion is set to 1.0000

**Comment by mpalasis** [comment]
Loaded this on my staging site, (dev mode enabled, errors enabled etc)
I see no reports, no new error log entries no php errors no apache errors.

Anything I can edit in the code to activate debug msgs to see where it gets stuck?

**Comment by dmitridr** [comment]
From what you say, yes the program crashed when getting the sample products because `samples:` should not be empty, this is likely due to a runtime exception.

You can try some of the following to display the exception either on screen or within `/var/log` or whatever your logging directory is set to :
https://stackoverflow.com/questions/17143406/how-to-turn-on-magento-error-messages
https://ecommerce.aheadworks.com/kbase/magento/how-to-enable-error-and-exception-logging-in-magento.html
https://magento.stackexchange.com/questions/14207/exception-printing-is-disabled-by-default-for-security-reasons

If you can find the exception and the line of code it traces back to, we will be able to fix it.

**Comment by mpalasis** [comment]
on my staging site, all those settings are already applied, that's why I asked if there's a debug toggle in the extension itself, because I'm not getting any error messages anywhere, it's a silent failure.

**Comment by dmitridr** [comment]
There's no debug setting specific to our extension, I'm not sure why it's not printing any errors. If you're willing to share temporary credentials with us to your staging site, we can take a look and see if we can find where the problem is. We would also need permission to install/uninstall the extension. 

Our email is ads_extension@fb.com if you're interested. If not, I'm not sure how much we can help beyond what has been found in #11 and #21. 

One final thought : Do you have visible products on your staging site? Otherwise, `samples` will indeed be empty.

**Comment by mpalasis** [comment]
I gave a try feeding it into chromephp...
fae_index.php
`Mage::helper('firegento/log')->chromephp($samples);`
and I get
```
Error in event handler for (unknown): SyntaxError: Unexpected end of JSON input
    at _decode (chrome-extension://noaneddfkdjfnfdakjjmocngnfkfehhd/log.js:156:21)
    at _process (chrome-extension://noaneddfkdjfnfdakjjmocngnfkfehhd/log.js:164:26)
    at _processQueue (chrome-extension://noaneddfkdjfnfdakjjmocngnfkfehhd/log.js:148:13)
    at _run (chrome-extension://noaneddfkdjfnfdakjjmocngnfkfehhd/log.js:194:9)
    at chrome-extension://noaneddfkdjfnfdakjjmocngnfkfehhd/log.js:204:13
```
so I dug deeper in 
```
fetchFeedSamples
which calls generateFacebookProductSamples
which calls $feed->generate()
with the same results, so I switched to plain ol' 
`Mage::helper('firegento/log')->debug($samples);`
...this worked but the output file had the titles of some of the products have a bad character at the end.
with this hint, *I THINK* this is an issue with the extension not using mbstring functions, I'll go swap them out and get back to you in a few.

**Comment by mpalasis** [comment]
I was right

![tmp-snap-fbads](https://user-images.githubusercontent.com/37408939/37942838-bc1ab436-317d-11e8-987d-eba10d67fb51.JPG)


may I suggest you implement the suggestion in https://github.com/facebookincubator/facebook-for-magento/issues/19 ?

I did what punkstar sugested...
> substr and strlen in that file and replace with their multi-byte counterparts - mb_substr and mb_strlen

I wonder why this hasn't been put in the main trunk yet? 
It's a unicode world out there.

**Comment by mpalasis** [comment]
https://github.com/facebookincubator/facebook-for-magento/pull/45
there you go

**Comment by dmitridr** [comment]
Amazing! Thanks for debugging this @mpalasis this has been a problem for us for ages. Can't thank you enough, we'll bundle your PR into the next version ASAP!!

**Comment by dmitridr** [comment]
Btw, If you're interested in working more on this kind of work at FB email us your resume. I'd be happy to recommend you!

**Comment by dmitridr** [comment]
@mpalasis We bundled your fix in the new version [v2.4.1](https://github.com/facebookincubator/facebook-for-woocommerce/releases), thanks again!

@Sprite-IT could you try this new version and see if it helps?

**Comment by Sprite-IT** [comment]
@dmitridr Unfortunately this did not solve our problem. We still only see the blue facebook header and thats it after installing the new version of this module.

**Comment by mpalasis** [comment]
out of curiosity does 'samples:' get populated on your end?

**Comment by Sprite-IT** [comment]
I am not sure if it gets populated to be honest.
The logs dont show anything and i have no clue where else to check if the samples gets populated.

**Comment by Sprite-IT** [comment]
Hey, i have been looking some more but i still cant find out what exactly goes wrong.
Even with the new version installed i still get the same error as shown in our original question.

Could someone help me out on how i can see if the samples get populated?

**Comment by mpalasis** [comment]
view page source and look for `window.facebookAdsExtensionAjax` (around line 459 on my case)
after that there's about a hundred lines of javascript code that are the output of this module.
The error thrown about diaSettingId is likely caused by a syntax error somewhere below,
like it was in my case with a  store using non-Latin product names.

The javascript code here is generated via the php and a bug in the php can generate bad js code, so the first step is to see what in the js looks bad/misplaced/incomplete/missing... and then poke around the php

**Comment by dmitridr** [comment]
Wish there was a better way we could debug errors like this. Somehow we're not able to catch and surface the exceptions in this part of the PHP code that generates `samples`, I am still puzzled as to why.

@mpalasis if you have any recommendation about code we can add to make this type of problem easier to identify would love to add it in. We do have [exception catching logic](https://github.com/facebookincubator/facebook-for-magento/blob/2.4.0/app/code/community/Facebook/AdsExtension/Block/Adminhtml/Diaindex.php#L108) but it appears not to be working correctly.

**Comment by mpalasis** [comment]
Paranoia is the name of the game whenever I have to work on a 3rd party platform with 3rd party modules where I cannot be sure if it's even fully working.

A debug/troubleshooting 'mode' where it does not assume data methods get valid data, but checks every single one. ie. right before reaching fae_index or thereabout -- like a unit test... but not.

Since you can't compare what you got against some static 'expected' list of results, your best bet is likely a user driven check where they pick a product id, and you tell them what the system thinks  `foo` is; and they have to confirm if it's correct or not, then move to the next value.

The most likely points of failure are going to be `images`, `description` and `short_description`, over the years there have been lots of modules in the wild that do numerous custom things with those.

This is all assuming the module was successfully installed in the first place, which might not be true if the user used that old `Magento Connect`. It's notoriously known for it's silent failures. Your [documentation ](https://www.facebook.com/business/help/532749253576163) recommends people use `Magento connect`, this is likely the cause of some of the problems here. Experienced Magento admins know not to use it, but small store owners - who are also likely to be using a shared host - will try it, and they will never know if it installed successfully.

**Comment by Sprite-IT** [comment]
Thanks for the help about the javascript, i have looked into that and saw that the samples are being filled. I also saw that the setdiasettingId is being filled in, yet at the get it stays null. I have tried to manually set the diasettingid in there but no luck. The rest of the javascript seems to be fine though.

**Comment by mpalasis** [comment]
hmm diaSettingId get populated [here ](https://github.com/facebookincubator/facebook-for-magento/blob/dee5a3f5912c1a0cddfcbbf73508936cef8aea3f/app/design/adminhtml/default/default/template/facebook_ads_extension/fae_index.phtml#L42) ... accessor [here](https://github.com/facebookincubator/facebook-for-magento/blob/dee5a3f5912c1a0cddfcbbf73508936cef8aea3f/app/code/community/Facebook/AdsExtension/Block/Adminhtml/Diaindex.php#L113)
which means the check for `!= null`  passes but the returned value is still blank in your case?

does your DB have a set value for this config setting?

example for mine:

>  Showing rows 0 -  0 (1 total, Query took 0.0068 seconds.)
> SELECT *  FROM `core_config_data` WHERE `path` LIKE '%facebook_ads_toolbox/dia/setting/id%'
> 2044	default	0	facebook_ads_toolbox/dia/setting/id	172(...)

**Comment by Sprite-IT** [comment]
The check did not pass, thats why i tried to manually fill in a few combinations from another script that should set the diasetting. But i also checked in our database with the sql you gave us, and as expected there was no row with that field. Which means that our database does not have a value for this module to be loaded. Should the module automatically add a row for this after installing the module? Or do i have to manually add a row for this in our database? Because as far as i can see that is indeed our problem now that the database does not contain it.

**Comment by mpalasis** [comment]
aha finally a hint of where the problem starts, I'm hoping @dmitridr  can help you with this hint, cause I'm not that familiar with the inner workings of this other than digging in them when needed.

**Comment by mpalasis** [comment]
ahmm, this was sorta random, but from https://github.com/facebookincubator/facebook-for-magento/pull/52#issuecomment-380563599 I got the idea to look again and sure enough, samples uses `echo json_encode($samples);` but after following the rabbit hole to https://github.com/facebookincubator/facebook-for-magento/blob/dee5a3f5912c1a0cddfcbbf73508936cef8aea3f/app/code/community/Facebook/AdsExtension/Model/FBProductFeed.php#L587 
I see that it is something that was under consideration, at one point, but I don't see it being passed an `$escapefn` value into it... not from buildProductAttr at least.

https://github.com/facebookincubator/facebook-for-magento/blob/dee5a3f5912c1a0cddfcbbf73508936cef8aea3f/app/code/community/Facebook/AdsExtension/Model/FBProductFeed.php#L177

 maybe I'm missing it.
So, @dmitridr maybe just a quick test to verify that any non-alnum characters like single/double quotes in Product names, Product descriptions get treated appropriately? It's way down in the rabbit hole enough that a bug might be hiding there. ;)

**Comment by mpalasis** [comment]
follow-up 
> ,samples: [{"id":"1","title":"test\"","description":"test\"","link":"http:\/\/192.168.0.107\/magento\/index.php\/catalog\/product\/view\/id\/1\/s\/test\/","image_link":"http:\/\/192.168.0.107\/magento\/media\/catalog\/productno_selection","brand":"192.168.0.107","condition":"new","availability":"in stock","price":"123,00 EUR","short_description":"testttt\"","product_type":"","google_product_category":"","gender":""},{"id":"2","title":"test222'","description":"ettest 2'","link":"http:\/\/192.168.0.107\/magento\/index.php\/catalog\/product\/view\/id\/2\/s\/test222\/","image_link":"http:\/\/192.168.0.107\/magento\/media\/catalog\/productno_selection","brand":"192.168.0.107","condition":"new","availability":"in stock","price":"1.234,00 EUR","short_description":"test 2'","product_type":"","google_product_category":"","gender":""}]

double quotes are escaped: `"test\""`
single quotes are not: `"test222'"` 
But since all outer quotes are double, this should be fine I ...think.

**Comment by Sprite-IT** [comment]
@dmitridr @mpalasis 
I have tried to throw in an empty array in the json encode, aswell as i tried to return the no samples generated echo. However with both tested i still get the same js error. So it seems that my samples do not necessary break the plugin. Maybe it does help break the plugin but it seems to go wrong somewhere else.

Also @dmitridr  i just sended you the js in a mail.

**Comment by dmitridr** [comment]
@Sprite-IT I got your email. Unfortunately it seems the js you sent was truncated.

In the text file I see `catalog\/product\/view\/id\/2144\/s\/spicy-sca…` and then the output drops off. 
Is this exactly how it appears when you view source? or just a truncation when sending the JS to us? 

If it's just a truncation could you email the whole JS of your site on the page which says Facebook Ads Extension? Perhaps the problem is elsewhere. 

If it is really how it appears then it's very strange. As @mpalasis said, the most likely cause is special characters in the `samples` but if you replaced the `samples` with a blank array (you would have to do this replacement in php to return an empty array), that shouldn't be the problem.

**Comment by Sprite-IT** [comment]
@dmitridr The js i send to you is exactly what we see in the source. So it actually wont finish it. I have checked the product if there are any weird symbols or something like that that could be the issue but that is not the case as far as i can see. When i enter an empty array in here it does finish the entire script but i will still have a white screen without anything.

**Comment by dmitridr** [comment]
Hi @Sprite-IT, if you are still trying to get this to work can you try [v2.6.0](https://github.com/facebookincubator/facebook-for-magento/releases/tag/v2.6.0) of the extension? It contains a `Debug Mode` which should be able to help you diagnose the problem. Using this mode you can gain access to log files which should tell you where the problem is, if you post those here we should be able to diagnose the problem. Let's continue the discussion in #21 since it is the same general issue (blank screen).
