### ISSUE TITLE
Purchase Event error 

### ISSUE THREAD

**Issue by golifter** [facebookincubator/facebook-for-magento#55]
I'm receiving this issue:
We haven't detected the event Purchase coming from your pixel

can you help me please?

**Comment by dmitridr** [comment]
Hello,

(1) Can you confirm your version number that you are using for our extension? If it's not the latest one, I recommend an upgrade in case this is due to a bug that has since been fixed.
(2) Can you download and install the Facebook Pixel Helper Tool (Chrome Extension) then make a test purchase on your site? This is the definitive way to verify whether purchase is working or not.

This will enable us to get to the bottom of your problem. Thanks.

**Comment by golifter** [comment]
@dmitridr 
I have installed the Facebook Pixel Helper Tool and everything looks fine: 
<img width="382" alt="captura de tela 2018-04-19 as 14 19 20" src="https://user-images.githubusercontent.com/10635241/39008248-81b9c7fa-43de-11e8-9222-9e3b5b665d9b.png">

But the error still there:
<img width="1020" alt="captura de tela 2018-04-19 as 14 32 53" src="https://user-images.githubusercontent.com/10635241/39008294-9a5324a0-43de-11e8-85ce-a8a036af9528.png">

**Comment by dmitridr** [comment]
@golifter Thanks for testing it out. If the helper tool says it's working, 99% of the time it's working, so it could be an error in the reporting interface. Some more follow up questions:

(1) Can you provide a link to where you see this? 
(2) Can you double check that the Pixel ID shown by the helper tool matches the one you see in the interface where you see `Error` ?
(3) This may be due to `Advanced Matching` interfering with reporting. Advanced Matching can be turned off in the `Pixel` tab after hitting `Manage Settings`, I would try disabling this and doing another test purchase and seeing if it helps.

**Comment by dmitridr** [comment]
I'm closing this as it has been a while since you have responded. Hopefully you were able to resolve the issue, but if not feel free to open a new issue on us and reference this one.

From my observations, sometimes it takes a while for events to show up in events manager even though it's working.
