### ISSUE TITLE
Product feed to Facebook Page Shop

### ISSUE THREAD

**Issue by asatnikscales** [facebookincubator/facebook-for-magento#9]
Hi,

We're excited that the facebook-for-magento extension is able to send product catalogs to Facebook.  I can confirm that we are now able to tag these products in our Facebook Posts, which we've been waiting for.

However, it appears our product catalog isn't being synced to our page's shop section.  Can you tell me if this extension is supposed to send our product catalog to or facebook shop, or if it will only show up in the Facebook Business?

**Comment by bedroomathletics** [comment]
Doesn't look like at the moment. The WordPress version does so hopefully this is something to come :)

**Comment by tahoff** [comment]
@bedroomathletics is correct, this extension currently does not create a shop and the products are only synced with your product catalog.

**Comment by dmitridr** [comment]
There's a workaround you can use if you want to use this plugin with shops: currently the export of products happens through a product feed. If you set up a new product feed for your shops catalog using the same URL (within the catalog manager interface), you can effectively upload all the products to the shop as well.

Workaround aside, we can add an option to automatically create a shop for you during setup (using the Magento catalog), if this is something many people want.

**Comment by asatnikscales** [comment]
dmitridr - I understand that this plugin creates a feed and a FaceBook product catalog using that feed URL.  I see in the product catalog settings where that feed URL is defined.  

What I don't understand is what you mean by  "If you set up a new product feed for your shops catalog using the same URL (within the catalog manager interface), you can effectively upload all the products to the shop as well."

Do I just create a new catalog in Business Manager and use that same feed URL?  I don't see an option to link it to a shop when setting up a new catalog.

I must be missing something.

**Comment by dmitridr** [comment]
If you have a shop, or you have created a shop, this is backed by a catalog, and a catalog is created for you in the backend to store your product data.

In many cases you should be able to access this catalog in [www.facebook.com/products](https://www.facebook.com/products). If you can find this catalog, and create a 'Feed' for it using the provided options, if you provide the URL you mentioned (or even do a one-time upload), it should update your shop with these products.

Unfortunately, if you can't find your catalog in that location, you may need to know the specific catalog ID in order to do the above operations. The URL would then be something like `https://www.facebook.com/products/catalog/<your_catalog_id_goes_here>`

Admittedly this isn't a great workaround. We will likely provide shops capability in the near future but as an advanced feature within the setup steps. I'll update this issue when that is the case.

**Comment by asatnikscales** [comment]
@dmitridr Thanks for the info.  I'll work with FB support to get the old shop deleted so I can create a new one using the feed and your workaround.  The existing shop was integrated with a BigCommerce account, which has since been deleted which resulted in an orphaned shop I can't delete or modify.

**Comment by kabadabra** [comment]
Also been trying to get the shop feed working - Going to https://www.facebook.com/products does not show any other feeds other than the ones we already manually created. @dmitridr Is there a way to find the catalog id on the static shop page so that we can manually use https://www.facebook.com/products/catalog/<your_catalog_id_goes_here> for example?

**Comment by kabadabra** [comment]
@dmitridr "We will likely provide shops capability in the near future but as an advanced feature within the setup steps. I'll update this issue when that is the case."  <-- This would be great! The WooCommerce one works really well and haven't had hassles with it.

If the catalog feed could also populate/sync the shop section, that would be fantastic!

**Comment by dmitridr** [comment]
@kabadabra 

Glad you had a good experience with our WooCommerce extension. We probably won't enable the shops in Magento until we can resolve outstanding shops issues with WooCommerce (which will also happen for Magento, undoubtedly).

Regarding your question about the catalog id. There's no great way to get it if you manually create a shop, you would have to use API calls to get it. If you link us to your page, I can tell you what your catalog id is as a one-off request.

**Comment by asatnikscales** [comment]
@dmitridr I really hate asking for support on this issue here, but Facebook support hasn't been able to help me even after multiple interactions over several months.  You seem to have some inside knowledge on Facebook Shops and Catalogs - maybe you can at least provide some insight.  We used to have our Facebook shop linked to BigCommerce.  We've since moved away from BigCommerce and now use Magento.  However, it doesn't look like BigCommerce properly removes its link/configuration from our FB Shop, so the Shop is left in an unusable state where we can't configure, manage products or delete it.  And if we delete the product Catalog from BigCommerce in FB Business Manager, it breaks the shop completely and results in an error when we browse to it.  

Is there a way to completely delete our old Shop and recreate it using the FB API?  Or do you have any other insight that might help?

Again - I know this isn't exactly the most appropriate forum for this question, and I apologize.  We've been trying to work with BigCommerce and FaceBook support for many months to resolve this without success.

**Comment by dmitridr** [comment]
@asatnikscales 
Our support team is stretched a bit thin, but they do the best they can with what they've got. Sorry to hear that you've been stuck on this. I can try to disable the BC shop for you, if you like, I would need your page, and some form of assurance that you are the actual owner of the page. I can't recreate the shop for you, however. Though you may have success with the approach I outlined above if you create a self-serve shop (which should be possible after the BC shop is removed) and attach the Magento feed to the catalog.

**Comment by asatnikscales** [comment]
My end goal **_is_** to create a self-serve shop and attach the Magento feed to the catalog, but obviously this BC Shop is preventing that.  It would be great if you could remove that old BC shop for me!

I'll PM you on FB about ownership assurance.

**Comment by dmitridr** [comment]
We solved this issue offline via messenger a few weeks ago. If there's a follow-up feel free to open a new issue and reference this one.

**Comment by dmitridr** [comment]
Update on the original comment : 

Unfortunately, It's unlikely we will support shops in the near future. This is because our company focus has shifted from shops over to a new feature called [marketplace](https://www.facebook.com/marketplace). 

If despite that, many of you still really want this, we can add this as an 'advanced' option which is hidden and not visible by default for most users. Please open a new issue, since this one has been a little side tracked by other problems.

**Comment by dmitridr** [comment]
@asatnikscales  FYI : We finally supported shops in v2.4.0 of the plugin, so if you're still looking for a way to integrate the shop with your Magento products you can try that.

**Comment by IJSIJS** [comment]
Hi, 
I have set this up but the feed it not taking in my google_product_category, even though it is in my product data.

can you assis pls, i'm on magento 1.9.*
